version: 1.0
tests:
  contractTests:
    - openApiOperation: '*::/*'
      statusSuccess:
        enabled: true
    - openApiOperation: '*::/*'
      responseTime:
        enabled: false
        maxMs: 300
    - openApiOperation: '*::/*'
      contentType:
        enabled: true
    - openApiOperation: '*::/*'
      jsonBody:
        enabled: true
    - openApiOperation: '*::/*'
      schemaValidation:
        enabled: true
    - openApiOperation: '*::/*'
      headersPresent:
        enabled: true
  contentTests: []
  extendTests: []
  variationTests: []
overwrites:
  - openApiOperation: '*::/*'
    overwriteRequestQueryParams:
      - key: q
        value: sea
        overwrite: true
operationPreRequestScripts:
  - openApiOperation: 'GET::/search/*'
    scripts:
      - |
        var_id = pm.request.url.variables.indexOf('resource_type')
        pm.request.url.variables.idx(var_id).value = pm.iterationData.get('resource_type')