name: Build, test and publish container
on:
  push:
    tags:
      - '*'

jobs:
  build-test-push:
    uses: ./.github/workflows/ci-pipeline.yaml
    with:
      docker_folder: app/
      tag: kb-api
      push: true
    secrets:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
